// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgtkndradfrykyiaqwro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndGtuZHJhZGZyeWt5aWFxd3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjY3NjEsImV4cCI6MjA3MDU0Mjc2MX0.x0xIFb-8cm_78_Ke2_ZcCPENDdKf3RjNA6U4Phij8Cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});